<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.0.79</Version>
    <AssemblyVersion>1.0.79.0</AssemblyVersion>
    <FileVersion>1.0.79.0</FileVersion>
    <InformationalVersion>1.0.79</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Company>CNC Sync</Company>
    <Product>CNC Sync</Product>
  </PropertyGroup>
</Project>
