<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CBWSSSync.Core\CBWSSSync.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
